apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: devops-tools
  labels:
    app: jenkins
spec:
  containers:
  - name: dnsutils
    image: dvbridges/db-dnsutils:latest
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
    ports:
      - name: httpport
        containerPort: 8080
      - name: jnlpport
        containerPort: 50000
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add: [NET_ADMIN, CAP_SYS_ADMIN]
  restartPolicy: Always