apiVersion: v1
kind: Pod
spec:
  containers:
  - env:
    - name: "JENKINS_URL"
      value: "http://192.168.158.8:8080/"
    name: jnlp
    image: jenkins/inbound-agent:4.3-4-jdk11
    command: ["/bin/sh","-c", "sleep 30; /usr/local/bin/jenkins-agent"]